In [1]:
import os
from matplotlib.image import imread
import numpy as np
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from NN import NN
from helper_fns import prepare_train_test_mnist

In [2]:
path = os.getcwd()
data_path = os.path.join(os.path.dirname(path),"Data","MNIST")

In [3]:
data_path

'H:\\sonu\\tipr\\Assignment2\\Data\\MNIST'

In [4]:
data,label = prepare_train_test_mnist(data_path)

In [5]:
data.shape,label.shape

((42000, 784), (42000,))

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    data, label, test_size=0.50, random_state=42,shuffle = True)

In [7]:
X_test.shape, X_train.shape

((21000, 784), (21000, 784))

In [8]:
y_tr_one_hot = np.zeros((y_train.shape[0],10))
y_test_one_hot = np.zeros((y_test.shape[0],10))
for i in range(y_train.shape[0]):
    y_tr_one_hot[i,y_train[i]] = 1
for i in range(y_test.shape[0]):
    y_test_one_hot[i,y_test[i]] = 1

In [9]:
y_tr_one_hot[0], y_tr_one_hot[1]

(array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]))

In [10]:
y_tr_one_hot.shape

(21000, 10)

In [11]:
net_3 = NN(hidden_layer=[30,30,30], activation=["swish","relu","relu"], 
         input_dim=784,output_dim=10, momentum = 0.1)

In [12]:
loss = net_3.fit_batch(X_train,y_tr_one_hot,epochs=2,lr=0.0001,batch_size=200)

epoch = 1 loss =1.0750551565745363
epoch = 2 loss =0.3684404489550846
training done


In [14]:
loss = net_3.fit_batch(X_train,y_tr_one_hot,epochs=4,lr=0.0001,batch_size=200)

epoch = 1 loss =0.20665918000077627
epoch = 2 loss =0.1720252758917801
epoch = 3 loss =0.15272799138246182
epoch = 4 loss =0.1387107966787227
training done


In [16]:
import pickle
with open("net_mnist.pickle","wb") as f:
    pickle.dump(net_3,f,pickle.HIGHEST_PROTOCOL)

In [17]:
pred_vals = net_3.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score

In [19]:
accuracy_score(y_test,pred_vals)

0.9443809523809524

In [18]:
from sklearn.metrics import f1_score
print(f1_score(y_test, pred_vals, average='macro'))
f1_score(y_test, pred_vals, average='micro') 

0.9360774615354647


0.9368571428571428

In [ ]:
net_4 = NN(hidden_layer=[30,30,30,10], activation=["swish","relu","relu","relu"], 
         input_dim=784,output_dim=10, momentum = 0.1)
loss = net_4.fit_batch(X_train,y_tr_one_hot,epochs=2,lr=0.0001,batch_size=200)

In [19]:
net_2 = NN(hidden_layer=[30,30], activation=["relu","relu"], 
         input_dim=784,output_dim=10, momentum = 0.1)

In [20]:
loss = net_2.fit_batch(X_train,y_tr_one_hot,epochs=10,lr=0.0001,batch_size=200)

H:\sonu\tipr\Assignment2\src\NN.py:8: RuntimeWarning: divide by zero encountered in log
  return np.sum(-np.log(pred_array[np.where(true_array==1)]))


epoch = 1 loss =inf
epoch = 2 loss =2.3019946685095234
epoch = 3 loss =2.301672942496468
epoch = 4 loss =2.3014738527496332
epoch = 5 loss =2.301350980216322
epoch = 6 loss =2.301275348876181
epoch = 7 loss =2.3012289290241705
epoch = 8 loss =2.3012005317645876
epoch = 9 loss =2.3011832289082714
epoch = 10 loss =2.301172738851732
training done


In [52]:
loss = net_2.fit_batch(X_train,y_tr_one_hot,epochs=50,lr=0.01, batch_size=200)

epoch = 1 loss =2.303592056619928
epoch = 2 loss =2.303689883780238
epoch = 3 loss =2.3036898837802378
epoch = 4 loss =2.3036898837802378
epoch = 5 loss =2.3036898837802378
epoch = 6 loss =2.3036898837802378
epoch = 7 loss =2.3036898837802378
epoch = 8 loss =2.3036898837802378
epoch = 9 loss =2.3036898837802378
epoch = 10 loss =2.3036898837802378
epoch = 11 loss =2.3036898837802378
epoch = 12 loss =2.3036898837802378
epoch = 13 loss =2.3036898837802378
epoch = 14 loss =2.3036898837802378
epoch = 15 loss =2.3036898837802378
epoch = 16 loss =2.3036898837802378
epoch = 17 loss =2.3036898837802378
epoch = 18 loss =2.3036898837802378
epoch = 19 loss =2.3036898837802378
epoch = 20 loss =2.3036898837802378
epoch = 21 loss =2.3036898837802378
epoch = 22 loss =2.3036898837802378
epoch = 23 loss =2.3036898837802378
epoch = 24 loss =2.3036898837802378
epoch = 25 loss =2.3036898837802378
epoch = 26 loss =2.3036898837802378
epoch = 27 loss =2.3036898837802378


KeyboardInterrupt: 

In [33]:
loss = net_2.fit_batch(X_train,y_tr_one_hot,epochs=10,lr=0.005,batch_size=200)

epoch = 1 loss =2.3061643041848674
epoch = 2 loss =2.306626550278871
epoch = 3 loss =2.3066265516320925
epoch = 4 loss =2.3066265516321005
epoch = 5 loss =2.3066265516321005
epoch = 6 loss =2.3066265516321005
epoch = 7 loss =2.3066265516321005
epoch = 8 loss =2.3066265516321005
epoch = 9 loss =2.3066265516321005
epoch = 10 loss =2.3066265516321005
training done


In [34]:
loss = net_2.fit_batch(X_train,y_tr_one_hot,epochs=10,lr=0.01,batch_size=200)

epoch = 1 loss =2.313841236045094
epoch = 2 loss =2.314299172427083
epoch = 3 loss =2.314299172433143
epoch = 4 loss =2.314299172433106
epoch = 5 loss =2.314299172433106
epoch = 6 loss =2.314299172433106


KeyboardInterrupt: 

In [30]:
a =np.array([[1,2,3],[3,2,1]])
np.argmax(a,axis=1)

array([2, 0], dtype=int64)

In [63]:
loss = net.fit_batch(X_train,y_tr_one_hot,epochs=12,lr=0.01,batch_size=200)

epoch = 1 loss =1.969155621419261
epoch = 2 loss =1.9686051929685253
epoch = 3 loss =1.968283035501524
epoch = 4 loss =1.968098827096417
epoch = 5 loss =1.9679794014897287
epoch = 6 loss =1.9678956405439196
epoch = 7 loss =1.9678336239231653
epoch = 8 loss =1.9677858487283846
epoch = 9 loss =1.9677479106121551
epoch = 10 loss =1.9677170528588963
epoch = 11 loss =1.9676914613873289
epoch = 12 loss =1.9676698933790893
training done


In [64]:
loss = net.fit_batch(X_train,y_tr_one_hot,epochs=12,lr=0.04,batch_size=200)

epoch = 1 loss =1.9791090284300783
epoch = 2 loss =1.979316276777669
epoch = 3 loss =1.979287547687667
epoch = 4 loss =1.979267263272366
epoch = 5 loss =1.979252172455619
epoch = 6 loss =1.9792405048685808
epoch = 7 loss =1.9792312133518222
epoch = 8 loss =1.9792236386262012
epoch = 9 loss =1.9792173448152401
epoch = 10 loss =1.9792120321595432
epoch = 11 loss =1.9792074877074097
epoch = 12 loss =1.9792035560002128
training done


In [23]:
loss = net.fit_batch(X_train,y_tr_one_hot,epochs=2,lr=0.0005,batch_size=200)

epoch = 1 loss =2.301578225014236
epoch = 2 loss =2.301520858452029
training done


In [24]:
loss = net.fit_batch(X_train,y_tr_one_hot,epochs=2,lr=0.001,batch_size=200)

epoch = 1 loss =2.301644540509039
epoch = 2 loss =2.301674019277117
training done


In [25]:
loss = net.fit_batch(X_train,y_tr_one_hot,epochs=4,lr=0.0001,batch_size=200)

epoch = 1 loss =2.3014669635944167
epoch = 2 loss =2.3014273358569963
epoch = 3 loss =2.301403042995998
epoch = 4 loss =2.3013880401177196
training done


In [33]:
net2 = NN(hidden_layer=[30,30], activation=["relu","relu"], 
         input_dim=784,output_dim=10,momentum= 0.1)
loss = net2.fit_batch(X_train,y_tr_one_hot,epochs=20,lr=0.0001,batch_size=200)

epoch = 1 loss =4.11449615926462
epoch = 2 loss =2.033490088291349
epoch = 3 loss =2.022017392097872
epoch = 4 loss =2.013765864485916
epoch = 5 loss =2.0075664822386585
epoch = 6 loss =2.0027476327373965
epoch = 7 loss =1.9988985466771148
epoch = 8 loss =1.9957551501849138
epoch = 9 loss =1.9931405735454135
epoch = 10 loss =1.9909321971463951
epoch = 11 loss =1.98904246813658
epoch = 12 loss =1.9874072593414323
epoch = 13 loss =1.9859785486965935
epoch = 14 loss =1.9847196700140726
epoch = 15 loss =1.9836021457303699
epoch = 16 loss =1.9826035219519116
epoch = 17 loss =1.9817058554619804
epoch = 18 loss =1.9808946350093863
epoch = 19 loss =1.980157998207269
epoch = 20 loss =1.9794861536558948
training done


In [34]:
loss = net2.fit_batch(X_train,y_tr_one_hot,epochs=4,lr=0.001,batch_size=200)

epoch = 1 loss =1.977038458769672
epoch = 2 loss =1.9739261768582055
epoch = 3 loss =1.9721096264575857
epoch = 4 loss =1.9709243745791505
training done


In [35]:
loss = net2.fit_batch(X_train,y_tr_one_hot,epochs=2,lr=0.002,batch_size=200)

epoch = 1 loss =1.9699684121555023
epoch = 2 loss =1.9690407791704079
training done


In [36]:
loss = net2.fit_batch(X_train,y_tr_one_hot,epochs=10,lr=0.002,batch_size=200)

epoch = 1 loss =1.9684145782020532
epoch = 2 loss =1.967978506390114
epoch = 3 loss =1.9676573748252135
epoch = 4 loss =1.9674110034488925
epoch = 5 loss =1.9672159957744997
epoch = 6 loss =1.9670578000470453
epoch = 7 loss =1.9669268889476006
epoch = 8 loss =1.9668167626570496
epoch = 9 loss =1.9667228344771366
epoch = 10 loss =1.9666417750457823
training done


In [37]:
loss = net2.fit_batch(X_train,y_tr_one_hot,epochs=10,lr=0.008,batch_size=200)

epoch = 1 loss =1.967719222119749
epoch = 2 loss =1.9676709977974003
epoch = 3 loss =1.9675485273118252
epoch = 4 loss =1.9674599049201187
epoch = 5 loss =1.9673927869326668
epoch = 6 loss =1.967340186289589
epoch = 7 loss =1.9672978492123836
epoch = 8 loss =1.9672630369296968
epoch = 9 loss =1.9672339060068358
epoch = 10 loss =1.967209169958365
training done


In [38]:
net1 = NN(hidden_layer=[40], activation=["swish"], 
         input_dim=784,output_dim=10,momentum = 0.4)
loss = net1.fit_batch(X_train,y_tr_one_hot,epochs=10,lr=0.0001,batch_size=200)

epoch = 1 loss =4.433801039178389
epoch = 2 loss =2.302101165295786
epoch = 3 loss =2.301809146342971
epoch = 4 loss =2.301632722340654
epoch = 5 loss =2.301526099539507
epoch = 6 loss =2.3014616097052185
epoch = 7 loss =2.30142255408468
epoch = 8 loss =2.301398860165759
epoch = 9 loss =2.301384452962038
epoch = 10 loss =2.301375667370853
training done


In [39]:
loss = net3.fit_batch(X_train,y_tr_one_hot,epochs=10,lr=0.01,batch_size=200)

epoch = 1 loss =2.303775149004516
epoch = 2 loss =2.303931856824324
epoch = 3 loss =2.303931856824324
epoch = 4 loss =2.303931856824324
epoch = 5 loss =2.303931856824324
epoch = 6 loss =2.303931856824324
epoch = 7 loss =2.303931856824324
epoch = 8 loss =2.303931856824324
epoch = 9 loss =2.303931856824324
epoch = 10 loss =2.303931856824324
training done
